name: Bot Auto-Merge
description: Allow a bot to auto-merge when all required checks have passed
author: domix24

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: git-merge
  color: green

inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'
  token:
    description: Your GitHub token
    required: true
    default: secrets.github_token

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node24
  main: dist/index.js
